#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

grep -Fq 'CC_CONNECT_SOURCE="${CC_CONNECT_SOURCE:-lazycat}"' "$ROOT/install.sh"
grep -Fq 'QClaw runtime 使用 QClaw 自带模型路由，跳过 OpenClaw provider preset' "$ROOT/install.sh"
grep -Fq 'AGENT_WORKSPACE="$QCLAW_HOME/workspace-$AGENT_ID"' "$ROOT/install.sh"
grep -Fq 'name = identity.get("name") or agent_id' "$ROOT/install.sh"
grep -Fq '[string]$CcConnectSource = "lazycat"' "$ROOT/install.ps1"
grep -Fq '[ValidateSet("openclaw","hermes","qclaw")]' "$ROOT/install.ps1"
grep -Fq '[switch]$UninstallAllCcConnect' "$ROOT/install.ps1"
grep -Fq 'Sync-QClawRuntime' "$ROOT/install.ps1"
grep -Fq '@("--agent-id", $AgentId, "--runtime", $Runtime)' "$ROOT/install.ps1"
grep -Fq 'QClaw 主模型继承' "$ROOT/install.ps1"
grep -Fq 'name = identity.get("name") or agent_id' "$ROOT/install.ps1"
grep -Fq 'OPENCLAW_CONFIG="${OPENCLAW_CONFIG:-$OPENCLAW_HOME/openclaw.json}"' "$ROOT/nako/scripts/lib.sh"
grep -Fq 'CONFIG="${OPENCLAW_CONFIG:-$OPENCLAW_HOME/openclaw.json}"' "$ROOT/nako/scripts/detect-models.sh"
grep -Fq 'CC_CONNECT_SOURCE="${CC_CONNECT_SOURCE:-lazycat}"' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'elif [ "$CC_CONNECT_SOURCE" = "lazycat" ] || [ "$CC_CONNECT_SOURCE" = "auto" ]; then' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'CC_CONNECT_GO_DOWNLOAD_VERSION="${CC_CONNECT_GO_DOWNLOAD_VERSION:-1.25.0}"' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'https://dl.google.com/go/go${CC_CONNECT_GO_DOWNLOAD_VERSION:-1.25.0}.linux-${arch}.tar.gz' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'CodeEagle/cc-connect 安装失败；请修复网络/Go 环境后重跑' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'should_npm_fallback' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq -- '--uninstall' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq -- '--uninstall-all' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'remove_cc_connect_project' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'uninstall_cc_connect_all' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq '.cc-connect.bak-uninstall-all-' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'ps -eo pid=,args=' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'looks_like_cc_connect_main(args)' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'openclaw|hermes|qclaw)' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'QCLAW_OPENCLAW_MJS' "$ROOT/scripts/cc-connect-setup.sh"
grep -Fq 'sync_qclaw_runtime' "$ROOT/install.sh"
grep -Fq 'f"  - name: {yaml_quote(name)}"' "$ROOT/install.sh"
! grep -Fq 'f"  {name}:"' "$ROOT/install.sh"
grep -Fq 'https://cdn.jsdelivr.net/gh/Lovappen/MetaPact@${AGENTS_REF}/install.sh' "$ROOT/scripts/nako-agent-factory/install.sh"
grep -Fq 'https://cdn.jsdelivr.net/gh/Lovappen/MetaPact@{AGENTS_REF}/install.sh' "$ROOT/scripts/nako-agent-factory/nako-server.py"

echo "cc-connect default source checks passed"
